### ISSUE TITLE
Toolbar doesn't behave nicely at small web browser widths

### ISSUE THREAD

**Issue by decimix** [jacobrec/spear-website#20]
Once the web browser's width becomes less than the minimum width of the toolbar, the toolbar wraps onto the next line. This may be related to issue #5.

**Comment by jacobrec** [comment]
I believe this should be an easy fix. in spear-website/src/app/site/app.component.ts on line 33 we check if the width is smaller then the height, and if it is, it shows the mobile "more" three dots instead of the tabs, it could probably be changed to fix this issue
