### ISSUE TITLE
Homepage title

### ISSUE THREAD

**Issue by cgarros** [jacobrec/spear-website#27]
![issue3 title](https://user-images.githubusercontent.com/43425964/51639000-177b9b00-1f1d-11e9-8213-518e5747480d.jpg)

**Comment by jacobrec** [comment]
I did as much as I could here, but you need to suggest a font

**Comment by cgarros** [comment]
The font I used was a font called HP Simplified. I think it looks nice

**Comment by jacobrec** [comment]
Do you know if we can use that font? What's the licence?

**Comment by jacobrec** [comment]
To be safe, can you pick a font from [this website](https://fonts.google.com/)?

**Comment by jacobrec** [comment]
Font is fine
